# -*- coding: utf-8 -*-
"""Amanjakhetiya_9918103209_F8_OSS_LAB7.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1atwTJLJW-P0gjQtXf8LN9Qo5YfsKuUJB
"""

from google.colab import files
files.upload()

import pandas as pd
import numpy as np

data=pd.read_csv("Automobile_data.csv")
data.head()

data.tail()

data.replace(['?'],['Nan'])
data.replace(['n.a'],['Nan'])

volvo=data[data['company']=='volvo']
print(volvo)

data['company'].value_counts()

company = data.groupby('company')
price = company['company','price'].max()
price

mileage = company['company','average-mileage'].mean()
mileage

Car_Price = {'Company': ['Toyota', 'Honda', 'BMV', 'Audi'], 'Price': [23845, 17995,
135925, 71400]}
Car_Price_Data=pd.DataFrame.from_dict(Car_Price)

Car_Horsepower = {'Company': ['Toyota', 'Honda', 'BMV', 'Audi'], 'horsepower': [141, 80,
182, 160]}
Car_Horsepower_Data=pd.DataFrame.from_dict(Car_Horsepower)

merged=pd.merge(Car_Price_Data,Car_Horsepower_Data, on ='Company')
merged

